from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from importlib.resources import as_file, files
from pathlib import Path
from typing import Any

import matplotlib as mpl
from matplotlib.axes import Axes

from axiomfig.template_helpers import apply_axis_contract


class StyleConflictError(ValueError):
    """Raised when two style layers claim the same rcParam without a contract."""


LAYER_ORDER = ("base", "geometry", "typography", "colors", "plot", "language", "rendering")
ALLOWED_OVERRIDES = {
    ("base", "plot"): {"xtick.direction", "ytick.direction"},
}


@dataclass(frozen=True)
class StyleSelection:
    geometry: str = "single-column"
    typography: str = "sans"
    colors: str = "default"
    plot: str = "line"
    language: str = "multilingual"
    rendering: str = "vector"
    base: str = "publication"

    def paths(self, style_root: Any | None = None) -> list[Any]:
        if style_root is None:
            style_root = files("axiomfig").joinpath("resources", "styles")
        selections = {
            "base": self.base,
            "geometry": self.geometry,
            "typography": self.typography,
            "colors": self.colors,
            "plot": self.plot,
            "language": self.language,
            "rendering": self.rendering,
        }
        paths = [style_root / layer / f"{selections[layer]}.mplstyle" for layer in LAYER_ORDER]
        missing = [path for path in paths if not path.is_file()]
        if missing:
            rendered = ", ".join(str(path) for path in missing)
            raise FileNotFoundError(f"Missing style module(s): {rendered}")
        return paths


@dataclass(frozen=True)
class ComposedStyle:
    paths: tuple[Any, ...]
    params: mpl.RcParams


def apply_tick_contract(axes: Axes, *, filled: bool) -> None:
    """Apply deterministic ticks after the selected plot type is known.

    Linear axes receive one minor tick per major interval. Logarithmic axes
    retain Matplotlib's mathematically meaningful minor locator.
    """
    apply_axis_contract(axes, surface="filled" if filled else "open")


def _layer_name(path: Any) -> str:
    return path.parent.name


def _load_style(path: Any) -> mpl.RcParams:
    with as_file(path) as materialized:
        return mpl.rc_params_from_file(materialized, fail_on_error=True, use_default_template=False)


def compose_styles(paths: Iterable[Any]) -> ComposedStyle:
    ordered = tuple(paths)
    merged = mpl.RcParams()
    owners: dict[str, tuple[str, Any]] = {}

    for path in ordered:
        if not path.is_file():
            raise FileNotFoundError(path)
        layer = _layer_name(path)
        params = _load_style(path)
        for key, value in params.items():
            if key in owners:
                prior_layer, prior_path = owners[key]
                allowed = key in ALLOWED_OVERRIDES.get((prior_layer, layer), set())
                if not allowed:
                    raise StyleConflictError(
                        f"Undeclared style conflict for {key}: {prior_path} -> {path}"
                    )
            merged[key] = value
            owners[key] = (layer, path)

    return ComposedStyle(paths=ordered, params=merged)


def write_composed_style(paths: Iterable[Any], output: Path) -> Path:
    composed = compose_styles(paths)
    output.parent.mkdir(parents=True, exist_ok=True)
    chunks = ["# Generated by AxiomFig. Later layers override only declared keys.\n"]
    for path in composed.paths:
        chunks.append(f"\n# --- {path.parent.name}/{path.name} ---\n")
        chunks.append(path.read_text(encoding="utf-8").rstrip() + "\n")
    output.write_text("".join(chunks), encoding="utf-8")
    return output
